# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'roomiesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    
  # Pods for roomiesApp
# pod 'SideMenu', '~> 6.0'
# pod 'SideMenuSwift'
 pod 'SwipeableTabBarController'
end
